### ISSUE TITLE
documentation, how-to, samples and examples

### ISSUE THREAD

**Issue by shobnaren** [antonio-hickey/TradovatePy#2]
Can you please add samples

**Comment by antonio-hickey** [comment]
Sure, anything specific you'd like samples on?

**Comment by shobnaren** [comment]
start from login, order submission, order status, cancel order, open positions and close all open position, flip position (long to short, short to long) etc.

**Comment by shobnaren** [comment]
sample code:
`import os
import asyncio

from TradovatePy.models.session import Session
from TradovatePy.accounting import Accounting

params = {
"environment": os.getenv("TO_ENV"),
"username": os.getenv("TO_USERID"),
"password": os.getenv("TO_PASSWD"),
"secret_key": os.getenv("TO_SECRET"),
"device_id": os.getenv("TO_DEVID"),
"app_version": os.getenv("TO_APPVER"),
"app_id": os.getenv("TO_APPID"),
"cid": os.getenv("TO_CID"),
}

s = Session(**params)
if True:
    a = Accounting(s)
    out = asyncio.run(a.account_list())
    print(out)`

but this one - throws below error as providing the account_list response - https://bugs.python.org/issue36709
Is there any safe handling of it - is there sample further or better way of using code - please share.

**Comment by antonio-hickey** [comment]
Hey sorry, I have creating samples and documentation on my todo list just been flooded with work stuff recently.

I think this should work:
```python
import os
import asyncio

from TradovatePy.models.session import Session
from TradovatePy import accounting

params = {
    "environment": os.getenv("TO_ENV"),
    "username": os.getenv("TO_USERID"),
    "password": os.getenv("TO_PASSWD"),
    "secret_key": os.getenv("TO_SECRET"),
    "device_id": os.getenv("TO_DEVID"),
    "app_version": os.getenv("TO_APPVER"),
    "app_id": os.getenv("TO_APPID"),
    "cid": os.getenv("TO_CID"),
}

s = Session(**params)
out = asyncio.run(accounting.account_list(s))
print(out)
```

**Comment by grzesir** [comment]
Can you please add a working example of how to connect to tradeovate, get your account balances/positions and place a trade?

**Comment by antonio-hickey** [comment]
@shobnaren 

Sorry for wait this was just fixed: https://github.com/antonio-hickey/TradovatePy/commit/b589ad6633212a31fecc45ade537b0285f743464
